[config]

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/style.css"

[templates.mako]
input_path = "~/.config/matugen/templates/mako.config"
output_path = "~/.config/mako/config"
post_hook = 'makoctl reload 2>/dev/null'

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/config.rasi"

[templates.wlogout]
input_path = "~/.config/matugen/templates/wlogout.css"
output_path = "~/.config/wlogout/style.css"

[templates.quickshell]
input_path = "~/.config/matugen/templates/quickshell.json"
output_path = "~/.config/quickshell/colors.json"

[templates.yazi]
input_path = "/home/natto/.config/matugen/templates/yazi.toml"
output_path = "/home/natto/.config/yazi/theme.toml"

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = "~/.config/nvim/lua/config/colors.lua"

[templates.pure]
input_path = "~/.config/matugen/templates/pure.fish"
output_path = "~/.config/fish/pure-colors.fish"
post_hook = "fish ~/.config/fish/pure-colors.fish"

[templates.cava]
input_path = "~/.config/matugen/templates/cava.ini"
output_path = "~/.config/cava/config"
