hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("easy", { type = "spring", mass = 0.6, stiffness = 190, dampening = 14 })
hl.curve("workspaceSpring", { type = "spring", mass = 0.8, stiffness = 260, dampening = 30 })

hl.animation({ leaf = "global",        enabled = true, speed = 5,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 2.5, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 2.5, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 3.2, spring = "easy",         style = "gnomed" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 3.2, bezier = "almostLinear",       style = "gnomed" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 2.25, bezier = "quick" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.25, bezier = "quick" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 2.5,   spring = "workspaceSpring", style = "slide" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 2.5,   spring = "workspaceSpring", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 2.5,   spring = "workspaceSpring", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 1,   bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 2.5, bezier = "quick" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 2.5,    bezier = "quick", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 2.5,    bezier = "quick",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.75, bezier = "quick" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.75, bezier = "quick" })
