# --- CẤU HÌNH FOOT ---
shell=fish
term=foot
pad=6x6
bold-text-in-bright=yes
font=Maple Mono NF CN:size=14:weight=900
letter-spacing=0

[main]
include=/home/natto/.config/foot/themes.ini

[scrollback]
lines=10000

[cursor]
style=beam
beam-thickness=1.5

[key-bindings]
scrollback-up-page=Page_Up
scrollback-down-page=Page_Down
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
search-start=Control+f
font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

[search-bindings]
cancel=Escape
find-prev=Shift+F3
find-next=F3 Control+G
delete-prev-word=Control+BackSpace

[tweak]
font-monospace-warn=no

[mouse]
hide-when-typing=false
