[[mgr.prepend_keymap]]
on   = [ "<Space>", "l" ]
run  = "toggle"
desc = "Select/Deselect item"

[[mgr.prepend_keymap]]
on   = [ "<Space>", "h" ]
run  = "visual_mode"
desc = "Visual Line mode"

[[mgr.prepend_keymap]]
on   = [ "<C-k>" ]
run  = "yank"
desc = "Yank (copy)"

[[mgr.prepend_keymap]]
on   = [ "<C-j>" ]
run  = "paste"
desc = "Put (paste)"

[[mgr.prepend_keymap]]
on   = [ "<C-h>" ]
run  = "yank --cut"
desc = "Delete (cut)"

[[mgr.prepend_keymap]]
on   = [ "<C-l>" ]
run  = "remove --permanently"
desc = "Remove (delete without trash)"

[[mgr.prepend_keymap]]
on   = [ "<S-k>" ]
run  = "arrow top"
desc = "Go to root directory"

[[mgr.prepend_keymap]]
on   = [ "<S-j>" ]
run  = "arrow bot"
desc = "Go to home directory"

[[mgr.prepend_keymap]]
on   = [ "b" ]
run  = "plugin bookmarks mark"
desc = "Save bookmark"

[[mgr.prepend_keymap]]
on   = [ "`" ]
run  = "plugin bookmarks go"
desc = "Go to bookmark"

[[mgr.prepend_keymap]]
on   = [ "~" ]
run  = "plugin bookmarks clear"
desc = "Clear bookmark"

[[mgr.prepend_keymap]]
on   = [ "H" ]
run  = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on = "x"
run = 'shell "7z a \"%h.zip\" \"$@\"" --confirm'
desc = "Compress hovered file/folder to zip"
